## 📋 Plan of Action and Milestones (POA&M)

| Control Family                     | Control ID | Control Key                                | Weakness Description                          | Planned Action                                  | Responsible Party | Target Completion Date | Status       |
|-----------------------------------|------------|--------------------------------------------|------------------------------------------------|--------------------------------------------------|-------------------|------------------------|--------------|
| Configuration Management          | CM-3       | Configuration Change                        | No formal change control process              | Implement Jira-based approval workflow           | IT Admin          | 2025-08-15             | In Progress  |
| Configuration Management          | CM-6       | Configuration Settings                      | No baseline enforcement for config settings   | Apply CIS benchmarks and automate checks         | Security Team     | 2025-08-20             | Planned      |
| Identification & Authentication   | IA-2       | Identification & Authentication Policy      | No formal policy for ID/auth                  | Draft and approve policy document                | Compliance Lead   | 2025-08-10             | Planned      |
| Incident Response                 | IR-4       | Incident Handling                           | No documented incident handling procedures    | Create and train on incident handling playbook   | SOC Manager       | 2025-08-25             | Not Started  |
| Maintenance                       | MA-3       | Maintenance Tools                           | No control over tools used for maintenance    | Restrict tool usage and log access               | IT Ops            | 2025-08-18             | Planned      |
| Media Protection                  | MP-5       | Media Transport                              | No secure transport procedures for media      | Develop and enforce transport policy             | Security Officer  | 2025-08-22             | Planned      |
| Personnel Security                | PS-7       | Personnel Termination                        | No formal termination checklist               | Create checklist and automate access revocation  | HR & IT           | 2025-08-12             | In Progress  |
| Physical & Environmental Protection | PE-10    | Physical Entry Controls                      | No badge or access control system             | Install badge readers and log access             | Facilities Lead   | 2025-08-30             | Planned      |
| Planning                          | PL-4       | Rules of Behavior                            | No documented rules of behavior               | Draft and distribute rules to all employees      | Compliance Team   | 2025-08-14             | Planned      |
| Program Management                | PM-9       | Risk Assessment                              | No formal risk assessment process             | Conduct annual risk assessment using NIST        | Risk Manager      | 2025-08-28             | Not Started  |
